// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtv4MH5t-fIEHG06-Ouqvn-iAdzdRAjE0',
    appId: '1:116870087879:android:84ef17373cffed6745aae2',
    messagingSenderId: '116870087879',
    projectId: 'cotahub-brasil-genesis',
    storageBucket: 'cotahub-brasil-genesis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTYiabFdMjHr5MJA_omYyvLI3bYTPymuI',
    appId: '1:116870087879:ios:f2e68f8461031fcd45aae2',
    messagingSenderId: '116870087879',
    projectId: 'cotahub-brasil-genesis',
    storageBucket: 'cotahub-brasil-genesis.firebasestorage.app',
    iosBundleId: 'com.example.cotahub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTYiabFdMjHr5MJA_omYyvLI3bYTPymuI',
    appId: '1:116870087879:ios:f2e68f8461031fcd45aae2',
    messagingSenderId: '116870087879',
    projectId: 'cotahub-brasil-genesis',
    storageBucket: 'cotahub-brasil-genesis.firebasestorage.app',
    iosBundleId: 'com.example.cotahub',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUOlMkCSdQpC9cCYiywy4wWB4ER4AuE1I',
    appId: '1:116870087879:web:be056b625f0ae2eb45aae2',
    messagingSenderId: '116870087879',
    projectId: 'cotahub-brasil-genesis',
    authDomain: 'cotahub-brasil-genesis.firebaseapp.com',
    storageBucket: 'cotahub-brasil-genesis.firebasestorage.app',
    measurementId: 'G-JY4X2H5TQN',
  );
}
